[package]
name = "yt-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.11", features = ["native-tls", "json"]}
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
